global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "upload-service"
    static_configs:
      - targets: ["upload-service:3001"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq-exporter:9419"]

  - job_name: "minio"
    metrics_path: /minio/prometheus/metrics
    static_configs:
      - targets: ["minio:9000"]