server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318

ingester: {}

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces